site_name: Kumiki Docs
site_description: Kumiki ドキュメント（00_concept 版）
site_url: https://example.com
theme:
  name: material
  language: ja
  features:
  - navigation.instant
  - navigation.tracking
  - navigation.sections
  - navigation.top
  - content.code.copy
docs_dir: docs
use_directory_urls: true
plugins:
- search
markdown_extensions:
- admonition
- toc
- tables
- attr_list
- def_list
- md_in_html
- pymdownx.superfences: {}
- pymdownx.details: {}
- pymdownx.tabbed:
    alternate_style: true
nav:
- 00_Concept:
  - Kumiki 概念要件（Concept Requirements）: 00_concept/CR-KMK-00_concept_requirements.md
  - Kumiki ロードマップ（2025H2, 2週間スプリント）: 00_concept/ROADMAP.md
  - ROADMAP_BURNDOWN: 00_concept/ROADMAP_BURNDOWN.md
  - ROADMAP_DASHBOARD: 00_concept/ROADMAP_DASHBOARD.md
  - CRスタイルガイド（G/I/O/ACの推奨粒度）: 00_concept/STD-KMK-CR-STYLE-01.md
