# tools/docops_cli/config/id_rules.yml
id_regex: '^(CR|RS|HLF|FR|NFR|CN|ADR|TRACE|DD|TEST)-[A-Z0-9]{2,}-[0-9A-Za-z_.-]+$'
normalize:
  uppercase: true
  fullwidth_to_halfwidth: true
  trim_spaces: true
  collapse_dashes: true
series_rules:
  - series: 'FR-LOG-{NN}'
    path_glob: 'docs/**/FR-LOG-*.md'
    number_regex: '^FR-LOG-(?P<num>[0-9]+)$'
  - series: 'RS-OBS-{NN}'
    path_glob: 'docs/**/RS-OBS-*.md'
    number_regex: '^RS-OBS-(?P<num>[0-9]+)$'
rename_policy:
  strategy: 'canonical_wins'   # 'canonical_wins' | 'reassign_suffix' | 'ulid_tail'
  suffix_format: 'A,B,C'       # when reassign_suffix
candidate_selection:
  title_weight: 0.5
  tag_weight: 0.3
  path_weight: 0.2
  threshold: 0.80
stub_template:
  dir: 'docs/10_requirements'
  filename: '{ID}.md'
  frontmatter:
    type: 'placeholder'
    status: 'draft'
    tags: ['stub']
paths:
  include: ['docs/**/*.md']
  exclude: ['**/.obsidian/**','node_modules/**']
performance:
  time_budget_sec: 60
