# tools/docops_cli/config/scale_rules.yml
sizes: [300, 600, 1000]
eval:
  queries: 100
  topk: 3
thresholds:
  max_ci_minutes_at_1000: 60
  critical_violations_must_be_zero: true
  min_hit3_ratio: 0.60   # 参考下限（データ合成時）
seeds:
  docs_seed: 4242
  links_seed: 4243
paths:
  out_dir: artifacts/scale
  public_dir: public/scale
