# tools/docops_cli/config/trace_rules.yml
paths:
  include: ['docs/**/*.md']
  exclude: ['**/.obsidian/**', 'node_modules/**', 'docs/index.md', "docs/**/ROADMAP_BURNDOWN.md", "docs/**/ROADMAP_DASHBOARD.md"]

node_kinds:
  infer_from_id_prefix: true
  mapping:
    - prefix: 'CR'
      kind: 'CR'
    - prefix: 'RS'
      kind: 'RS'
    - prefix: 'HLF'
      kind: 'HLF'
    - prefix: 'FR'
      kind: 'FR'
    - prefix: 'NFR'
      kind: 'NFR'
    - prefix: 'CN'
      kind: 'CN'
    - prefix: 'ADR'
      kind: 'ADR'
    - prefix: 'TRACE'
      kind: 'TRACE'
    - prefix: 'DD'
      kind: 'DD'
    - prefix: 'TEST'
      kind: 'TEST'

version: 1
relations:
  - key: canonical_parent
    type: parent
    scalar: true

  - key: depends_on
    type: depends_on

  - key: refines
    type: refines

  - key: satisfies
    type: satisfies

  - key: integrates_with
    type: integrates_with

  - key: constrains
    type: constrains

  - key: supersedes
    type: supersedes

  - key: contributes_to
    type: contributes_to

  - key: satisfies_hlf
    type: satisfies_hlf

# 明示定義（FrontMatter）の他、本文で拾うときに「この接頭辞だけ」許可
accept_id_prefixes:
  - BG-KMK-
  - HLF-
  - KPI-
  - FR-
  - NFR-
  - CN-
  - RS-
  - DD-
  - TC-

# 旧→新の別名
aliases:
  - { alias: "BG-01",           target: "BG-KMK-01" }
  - { alias: "BG-02",           target: "BG-KMK-02" }
  - { alias: "BG-03",           target: "BG-KMK-03" }
  - { alias: "BG-04",           target: "BG-KMK-04" }
  - { alias: "BG-05",           target: "BG-KMK-05" }
  - { alias: "BG-06",           target: "BG-KMK-06" }
  - { alias: "CR-01",           target: "CR-KMK-01" }
  - { alias: "CR-02",           target: "CR-KMK-02" }
  - { alias: "CR-03",           target: "CR-KMK-03" }
  - { alias: "CR-04",           target: "CR-KMK-04" }
  - { alias: "CR-05",           target: "CR-KMK-05" }
  - { alias: "CR-06",           target: "CR-KMK-06" }
  - { alias: "CR-07",           target: "CR-KMK-07" }
  - { alias: "CR-08",           target: "CR-KMK-08" }
  - { alias: "CR-09",           target: "CR-KMK-09" }
  - { alias: "CR-10",           target: "CR-KMK-10" }
  - { alias: "CR-11",           target: "CR-KMK-11" }
  - { alias: "CR-12",           target: "CR-KMK-12" }
  - { alias: "CR-13",           target: "CR-KMK-13" }
  - { alias: "CR-14",           target: "CR-KMK-14" }
  - { alias: "CR-15",           target: "CR-KMK-15" }

suggest:
  threshold: 0.65
  strong_threshold: 0.8
  max_suggestions_per_file: 20
  heading_hints: ['関連', '関連HLF', '関連FR', '関連NFR', 'Related', 'References']
  alias_vocab_file: 'docs/_vocabulary.yml'
  score_weights:
    exact_id: 0.6
    heading_hint: 0.2
    structure_prox: 0.1
    alias_hint: 0.1

reachability:
  roundtrip_required_pairs:
    - from: 'RS'
      via: ['HLF','FR|NFR','TEST|TRACE']
      to: 'RS'
  important_node_kinds: ['RS','HLF','FR','NFR','CN']
  fail_on_cycle_for: ['refines','satisfies']

output:
  emit_dot: true
  formats: ['json','md']

performance:
  time_budget_sec: 60
