#!/usr/bin/env python3
import os, json, shutil, html

TITLE = os.environ.get("KUMIKI_INDEX_TITLE", "Kumiki — CI Gate Summary")
OUTDIR = "public"
ARTDIR = os.path.join(OUTDIR, "artifacts")

def link(path):
    return f'<li><a href="{html.escape(path)}">{html.escape(path)}</a></li>'

def main():
    os.makedirs(OUTDIR, exist_ok=True)
    os.makedirs(ARTDIR, exist_ok=True)
    paths = [
        "artifacts/gate/gate_summary.json",
        "artifacts/trace/graph.json",
        "artifacts/search/meta.json",
        "artifacts/secscan/report.json",
        "artifacts/reach/report.json",
        "artifacts/idcheck/report.json",
        "artifacts/i18n/report.json",
        "artifacts/impact/report.json",
    ]
    copied = []
    for p in paths:
        if os.path.exists(p):
            dst = os.path.join(ARTDIR, os.path.basename(p))
            try:
                shutil.copy2(p, dst)
                copied.append(dst.replace(OUTDIR + "/", ""))
            except Exception:
                pass
    links = "\n".join(link(p) for p in copied) if copied else "<li>No artifacts found</li>"
    html_text = f"""<!doctype html>
<html lang="en">
<meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>{html.escape(TITLE)}</title>
<style>body{{font-family:system-ui,-apple-system,Segoe UI,Roboto,Ubuntu,Helvetica,Arial,sans-serif;line-height:1.5;margin:2rem;max-width:1000px}}h1{{font-size:1.8rem;margin-bottom:.5rem}}</style>
<body>
<h1>{html.escape(TITLE)}</h1>
<p>Latest gate summary and key artifacts.</p>
<ul>
{links}
</ul>
<footer><small>Generated by make_index.py</small></footer>
</body>
</html>"""
    with open(os.path.join(OUTDIR, "index.html"), "w", encoding="utf-8") as f:
        f.write(html_text)

if __name__ == "__main__":
    main()
