site_name: Kumiki Docs
site_description: Kumiki ドキュメント（00_concept 版）
site_url: https://example.com
theme:
  name: material
  language: ja
  features:
  - navigation.instant
  - navigation.tracking
  - navigation.sections
  - navigation.top
  - content.code.copy
docs_dir: docs
use_directory_urls: true
plugins:
- search
markdown_extensions:
- admonition
- toc
- tables
- attr_list
- def_list
- md_in_html
- pymdownx.superfences: {}
- pymdownx.details: {}
- pymdownx.tabbed:
    alternate_style: true
nav:
- 00_Concept: []
