name: docops_approval_gate

'on':
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled, edited]
    paths:
      - '**'
      - '!**/*.png'
      - '!**/*.jpg'
      - '.github/workflows/docops_approval_gate.yml'

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: approval-gate-${{ github.ref }}
  cancel-in-progress: true

jobs:
  approval-gate:
    name: PR Approval Gate
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml

      - name: Run approval gate
        id: gate
        run: |
          mkdir -p artifacts/approval
          if [ -f tools/ci/approval_gate.py ]; then
            python tools/ci/approval_gate.py tools/docops_cli/config/approval_rules.yml artifacts/approval || echo "gate_exit=$?" >> $GITHUB_OUTPUT
          else
            echo "approval_gate.py not found; skipping"; echo "gate_exit=0" >> $GITHUB_OUTPUT
          fi

      - name: Upload approval artifacts
        uses: actions/upload-artifact@v4
        with:
          name: docops-approval
          path: artifacts/approval

      - name: Label when manual approval required
        if: failure() || steps.gate.outputs.gate_exit == '2'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr edit ${{ github.event.pull_request.number }} --add-label "needs-approval" || true
          gh pr edit ${{ github.event.pull_request.number }} --remove-label "automerge" || true
