name: docops_ann_swap

'on':
  pull_request:
    paths:
      - 'tools/docops_cli/connectors/**'
      - 'tools/docops_cli/config/ann_connectors.yml'
      - 'tools/docops_cli/ann_benchmark.py'
      - '.github/workflows/docops_ann_swap.yml'
  workflow_dispatch: {}

concurrency:
  group: ann-swap-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  ann_benchmark:
    name: ANN connector benchmark (matrix optional)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          # If project has specific requirements, install them
          for f in tools/ci/requirements.txt tools/docops_cli/requirements.txt requirements.txt; do
            [ -f "$f" ] && pip install -r "$f";
          done
          pip install pyyaml numpy

      - name: Run ANN benchmark
        run: |
          if [ -f tools/docops_cli/ann_benchmark.py ]; then
            python tools/docops_cli/ann_benchmark.py --config tools/docops_cli/config/ann_connectors.yml --out artifacts/ann_bench || true
          else
            echo "ann_benchmark.py not found; skipping"; exit 0
          fi

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ann-benchmark-artifacts
          path: artifacts/ann_bench
