name: docops_idcheck
on:
  pull_request:
    paths:
      - 'docs/**'
      - 'tools/docops_cli/**'
      - 'eval/id_cases.yaml'
      - '.github/workflows/docops_idcheck.yml'
jobs:
  idcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          pip install -U pip
          pip install pyyaml regex python-slugify
      - name: Verify & Suggest
        run: |
          python tools/docops_cli/idcheck.py verify             --rules tools/docops_cli/config/id_rules.yml             --out artifacts/idcheck --format json,md
          python tools/docops_cli/idcheck.py suggest             --rules tools/docops_cli/config/id_rules.yml             --out artifacts/idcheck --generate-stub
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: docops-idcheck-artifacts
          path: artifacts/idcheck
