name: docops_audit
on:
  pull_request:
    paths:
      - 'docs/**'
      - 'tools/docops_cli/**'
      - '.github/workflows/docops_audit.yml'
jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          pip install -U pip
          pip install pyyaml cryptography merklelib python-ulid
      - name: Append & Verify Ledger
        run: |
          python tools/docops_cli/audit.py append             --rules tools/docops_cli/config/audit_rules.yml             --out artifacts/ledger
          python tools/docops_cli/audit.py verify             --rules tools/docops_cli/config/audit_rules.yml             --ledger artifacts/ledger/audit.ndjson             --manifest artifacts/ledger/manifest.json             --pubkeys tools/docops_cli/config/audit_pubkeys.pem             --fail-on-missing --fail-on-broken-chain
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: docops-audit-ledger
          path: artifacts/ledger
