name: docops_ai_patch

'on':
  workflow_dispatch: {}

concurrency:
  group: ai-patch-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write   # if creating branches/PRs
  pull-requests: write

jobs:
  suggest:
    name: AI patch proposal (manual)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          # add project-specific deps if needed
          pip install pyyaml

      - name: Generate patch (dry-run)
        run: |
          if [ -f tools/docops_cli/ai_patch.py ]; then
            python tools/docops_cli/ai_patch.py --out artifacts/ai_patch || true
          else
            echo "ai_patch.py not found; skipping"; exit 0
          fi

      - name: Create PR (optional)
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          if [ -d artifacts/ai_patch ] && [ -n "$(ls -A artifacts/ai_patch 2>/dev/null)" ]; then
            echo "Preparing PR..."
            # Place holder: implement branch/commit/PR creation if desired.
            # gh pr create --title "AI patch proposal" --body "Automated suggestion" || true
          else
            echo "No patch produced; skipping PR creation."
          fi

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ai-patch-artifacts
          path: artifacts/ai_patch
