name: kumiki_ci_publish_plus

'on':
  pull_request:
    paths:
      - 'docs/**'
      - 'tools/**'
      - '.github/workflows/kumiki_ci_publish_plus.yml'
  push:
    branches: ['main']
    paths:
      - 'docs/**'
      - 'tools/**'
      - '.github/workflows/kumiki_ci_publish_plus.yml'

concurrency:
  group: kumiki-ci-publish-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  PYTHONUNBUFFERED: '1'

jobs:
  build_and_gate:
    name: Lint / Trace / Index / Gate / (MkDocs)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          # どこに置いてあっても拾えるように冗長に解決
          for f in tools/ci/requirements.txt tools/docops_cli/requirements.txt requirements.txt; do
            if [ -f "$f" ]; then pip install -r "$f"; fi
          done
          # 既知の不足（例：PyYAML, MkDocs）
          pip install pyyaml mkdocs mkdocs-material

      # --- DocOps: Lint / Trace / Index / Gate ---
      - name: Doc Lint
        run: |
          if [ -f tools/ci/doc_lint.py ]; then python tools/ci/doc_lint.py; fi

      - name: Emit Trace
        run: |
          if [ -f tools/ci/trace_emit.py ]; then python tools/ci/trace_emit.py; fi

      - name: Aggregate Gate
        run: |
          if [ -f tools/ci/aggregate_gate.py ]; then \
            python tools/ci/aggregate_gate.py tools/docops_cli/config/publish_rules.yml; \
          fi

      - name: Build site (MkDocs)
        run: |
          if [ -f mkdocs.yml ]; then mkdocs build -d public; else mkdir -p public; fi

      - name: Build public index
        env:
          KUMIKI_INDEX_TITLE: "Kumiki — CI Gate Summary"
        run: |
          if [ -f tools/ci/make_index.py ]; then python tools/ci/make_index.py; fi
          # public/index.html がない場合の保険
          if [ ! -e public/index.html ]; then echo "<h1>Kumiki</h1>" > public/index.html; fi

      # --- Pages: Configure / Upload は main push のときだけ ---
      - name: Configure Pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/configure-pages@v5

      - name: Upload pages artifact
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  publish:
    name: Deploy to GitHub Pages
    needs: build_and_gate
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    # Deploy に必要な最小権限だけ付与
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
