name: kumiki_ci_publish_plus

'on':
  pull_request:
    paths:
      - 'docs/**'
      - 'tools/**'
      - '.github/workflows/kumiki_ci_publish_plus.yml'
  push:
    branches: ['main']
    paths:
      - 'docs/**'
      - 'tools/**'
      - '.github/workflows/kumiki_ci_publish_plus.yml'

concurrency:
  group: kumiki-ci-publish-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    name: Build (Lint/Trace optional) + Pages:prepare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }

      - name: Install minimal deps
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml mkdocs mkdocs-material networkx

      # --- Optional: Doc Lint (あれば実行、無ければスキップ) ---
      - name: Run DocLint
        run: |
          python tools/ci/doc_lint.py check --rules tools/docops_cli/config/doclint_rules.yml --out artifacts/doclint --format json,md
      - name: Show DocLint summary
        if: always()
        run: |
          echo "==== DocLint report ===="
          cat artifacts/doclint/report.json || true
      - uses: actions/upload-artifact@v4
        with:
          name: docops-doclint
          path: artifacts/doclint


      # --- Optional: Trace（buildのみ） ---
      - name: Trace build (optional)
        run: |
          if [ -f tools/ci/trace.py ]; then
            python tools/ci/trace.py build --out artifacts/trace --format json,md
          else
            echo "no tools/ci/trace.py"
          fi

      # --- Site build ---
      - name: Build site (MkDocs)
        run: |
          if [ -f mkdocs.yml ]; then
            mkdocs build -d public
          else
            mkdir -p public && echo "<h1>Kumiki</h1>" > public/index.html
          fi

      # --- Pages: prepare（main pushのみ） ---
      - name: Configure Pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/configure-pages@v5

      - name: Upload pages artifact
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v3
        with: { path: public }

  publish:
    name: Pages:deploy (main only)
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
